controller_manager:
  ros__parameters:
    update_rate: 200
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    biped_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController


biped_joint_trajectory_controller:
  ros__parameters:
    joints:
      - l_abduction
      - l_hip_roll
      - l_knee_roll
      - l_foot_roll
      - r_abduction
      - r_hip_roll
      - r_knee_roll
      - r_foot_roll

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    allow_partial_joints_goal: true
