controller_manager:
  ros__parameters:
    update_rate: 200
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    biped_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

biped_joint_trajectory_controller:
  ros__parameters:
    joints:
      - l_abduction
      - l_hip_roll
      - l_knee_roll
      - r_abduction
      - r_hip_roll
      - r_knee_roll
      

    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

    allow_partial_joints_goal: true

    # 🔴 ADDED GAINS SECTION
    gains:
      l_abduction: {p: 1000.0, i: 10.0, d: 20.0}
      l_hip_roll:  {p: 2500.0, i: 10.0, d: 40.0}
      l_knee_roll: {p: 2500.0, i: 10.0, d: 40.0}
      r_abduction: {p: 1000.0, i: 10.0, d: 20.0}
      r_hip_roll:  {p: 2500.0, i: 10.0, d: 40.0}
      r_knee_roll: {p: 2500.0, i: 10.0, d: 40.0}
     